<a href="https://colab.research.google.com/github/oektomo/KelasRLG2/blob/master/05SarsaLFrozenLakeMedium.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://medium.com/swlh/introduction-to-reinforcement-learning-coding-sarsa-part-4-2d64d6e37617
# https://medium.com/swlh/introduction-to-reinforcement-learning-coding-q-learning-part-3-9778366a41c0
import gym
import numpy as np
import time, pickle, os

env = gym.make('FrozenLake-v0')

epsilon = 0.9
# min_epsilon = 0.1
# max_epsilon = 1.0
# decay_rate = 0.01

total_episodes = 10000
max_steps = 100

lr_rate = 0.81
gamma = 0.96

Q = np.zeros((env.observation_space.n, env.action_space.n))
    
def choose_action(state):
	action=0
	if np.random.uniform(0, 1) < epsilon:
		action = env.action_space.sample()
	else:
		action = np.argmax(Q[state, :])
	return action

def learn(state, state2, reward, action, action2):
	predict = Q[state, action]
	target = reward + gamma * Q[state2, action2]
	Q[state, action] = Q[state, action] + lr_rate * (target - predict)

# Start
rewards=0

for episode in range(total_episodes):
	t = 0
	state = env.reset()
	action = choose_action(state)
    
	while t < max_steps:
		#env.render()

		state2, reward, done, info = env.step(action)

		action2 = choose_action(state2)

		learn(state, state2, reward, action, action2)

		state = state2
		action = action2

		t += 1
		rewards+=1

		if done:
			break
  # epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode) 
  # os.system('clear')
	#	time.sleep(0.1)

    
print ("Score over time: ", rewards/total_episodes)
print(Q)

#with open("frozenLake_qTable_sarsa.pkl", 'wb') as f:
#	pickle.dump(Q, f)

Score over time:  7.8869
[[6.67117711e-04 6.08296411e-04 3.72464171e-03 4.91911110e-04]
 [2.89877090e-04 3.71758958e-04 4.44159610e-04 7.59382476e-04]
 [3.46213678e-04 4.87911502e-05 1.51722156e-04 1.07606541e-03]
 [2.29390526e-04 1.34712078e-06 4.06446224e-05 1.41407842e-04]
 [8.69681713e-04 9.59552103e-04 1.06223076e-04 2.06502938e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.09253438e-03 4.73925096e-06 5.61018692e-04 7.49127871e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.10481341e-03 8.96263360e-02 1.89746039e-04 2.74254660e-03]
 [5.91125609e-01 1.23085051e-01 9.15987072e-04 2.95287462e-02]
 [4.86013919e-03 2.01257233e-01 1.65745595e-02 1.48268435e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.76742939e-02 1.04511062e-01 3.47393338e-01 1.15294171e-01]
 [1.84002724e-01 4.77350695e-01 4.68784488e-01 8.58719648e-01]
 [0.00000000e+00 0.00000000e+0