<a href="https://colab.research.google.com/github/oektomo/KelasRLG2/blob/master/QLFrozenLakeMedium.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# https://medium.com/swlh/introduction-to-reinforcement-learning-coding-sarsa-part-4-2d64d6e37617
# https://medium.com/swlh/introduction-to-reinforcement-learning-coding-q-learning-part-3-9778366a41c0
import gym
import numpy as np
import time, pickle, os

env = gym.make('FrozenLake-v0')

epsilon = 0.9
total_episodes = 10000
max_steps = 100

lr_rate = 0.81
gamma = 0.96

Q = np.zeros((env.observation_space.n, env.action_space.n))
    
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def learn(state, state2, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = Q[state, action] + lr_rate * (target - predict)

# Start
for episode in range(total_episodes):
    state = env.reset()
    t = 0
    
    while t < max_steps:
        #env.render()

        action = choose_action(state)  

        state2, reward, done, info = env.step(action)  

        learn(state, state2, reward, action)

        state = state2

        t += 1
       
        if done:
            break

        #time.sleep(0.1)

print(Q)

#with open("frozenLake_qTable.pkl", 'wb') as f:
#    pickle.dump(Q, f)

[[6.75656231e-01 7.27682130e-01 6.19633239e-01 6.82092621e-01]
 [5.99306388e-01 6.07093807e-01 5.08063806e-01 6.23356613e-01]
 [6.50145068e-01 6.56228535e-01 2.52515466e-01 6.30323111e-01]
 [1.14786395e-01 6.67196984e-01 3.80184497e-03 6.84801656e-01]
 [7.66631253e-01 1.12320742e-01 6.96811824e-04 1.00814569e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.54389315e-01 2.57049790e-02 1.60031407e-01 3.94177296e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00147637e-01 6.77441207e-01 6.88730585e-01 7.44892894e-01]
 [6.33305669e-01 8.71536227e-01 3.23436930e-02 7.08745708e-01]
 [8.78378243e-01 7.78184830e-01 2.83448768e-02 1.59377855e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.01592277e-01 1.80432564e-01 8.84578283e-01 9.48439233e-01]
 [9.19240206e-01 9.27802111e-01 9.32246606e-01 9.71807448e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000